Update Dock+Terr+aws_cli

diff --git a/Dock+Terr+aws_cli b/Dock+Terr+aws_cli
--- a/Dock+Terr+aws_cli
+++ b/Dock+Terr+aws_cli
@@ -1,6 +1,7 @@
 #!/bin/bash
 # docker . Terraform , AWS CLI
-# Function to install Docker on Linux
+
+# Function to install Docker on Linux (Debian/Ubuntu)
 install_docker_linux() {
   echo "Installing Docker on Linux..."
   sudo apt update
@@ -15,7 +16,17 @@ install_docker_linux() {
   sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
 }
 
-# Function to install Terraform on Linux
+# Function to install Docker on RHEL/CentOS/Fedora
+install_docker_rhel() {
+  echo "Installing Docker on RHEL/CentOS/Fedora..."
+  sudo yum install -y yum-utils
+  sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
+  sudo yum install -y docker-ce docker-ce-cli containerd.io
+  sudo systemctl start docker
+  sudo systemctl enable docker
+}
+
+# Function to install Terraform on Linux (Debian/Ubuntu)
 install_terraform_linux() {
   echo "Installing Terraform on Linux..."
   sudo apt update && sudo apt install -y gnupg software-properties-common curl
@@ -25,9 +36,41 @@ install_terraform_linux() {
   sudo apt update && sudo apt install -y terraform
 }
 
-# Function to install AWS CLI on Linux
+# Function to install Terraform on RHEL/CentOS/Fedora
+install_terraform_rhel() {
+  echo "Installing Terraform on RHEL/CentOS/Fedora..."
+  sudo yum install -y yum-utils
+  sudo yum install -y dnf-plugins-core
+  sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
+  sudo dnf install terraform
+}
+
+# Function to install AWS CLI on Linux (Debian/Ubuntu)
 install_awscli_linux() {
   echo "Installing AWS CLI on Linux..."
+  
+  # Check if unzip is installed, if not, install it
+  if ! command -v unzip &> /dev/null; then
+    echo "unzip not found. Installing unzip..."
+    sudo yum install unzip -y
+  fi
+
+  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+  unzip awscliv2.zip
+  sudo ./aws/install
+  rm -rf aws awscliv2.zip
+}
+
+# Function to install AWS CLI on RHEL/CentOS/Fedora
+install_awscli_rhel() {
+  echo "Installing AWS CLI on RHEL/CentOS/Fedora..."
+  
+  # Check if unzip is installed, if not, install it
+  if ! command -v unzip &> /dev/null; then
+    echo "unzip not found. Installing unzip..."
+    sudo yum install unzip -y
+  fi
+
   curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
   unzip awscliv2.zip
   sudo ./aws/install
@@ -56,6 +99,11 @@ case "$OS" in
   Linux*)
     if grep -qi microsoft /proc/version; then
       install_wsl
+    elif [ -f /etc/redhat-release ]; then
+      # Check if it's a Red Hat-based system
+      install_docker_rhel
+      install_terraform_rhel
+      install_awscli_rhel
     else
       install_docker_linux
       install_terraform_linux
